apiVersion: v1
kind: Service
metadata:
  name: microservice-service
spec:
  type: NodePort
  ports:
    - port: 80           # The port the service listens on inside the cluster
      targetPort: 3000   # The containerPort target on your pods
      nodePort: 30080    # Exposes http://localhost:30080 via Minikube
  selector:
    app: my-microservice